language: java
jdk: oraclejdk8
dist: trusty
stages:
  - test
jobs:
  include:
    - stage: test
      script:
      - ./gradlew build jacocoTestReport sonarqube
addons:
  sonarcloud:
    organization: snemmani

