/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package design.patterns.java;

import design.patterns.java.snemmani.abstractFactory.CreditCardAbstractFactoryDemo;
import design.patterns.java.snemmani.factory.WebsiteFactoryMain;

public class App {
    public static void main(String[] args) {
        CreditCardAbstractFactoryDemo.main(args);
    }
}
