/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package design.patterns.java;

import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.*;


public class AppTest {
    @Test public void testAppHasAGreeting() {

    }
}
